version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-basic-01"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8qhwxc50qem5"
s3_prefix = "sam-basic-01"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
